apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cn67eswjz-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e720b0f5c0.l4eo.p3.openshiftapps.com/rhtap/rhtap-qe:7ce04bf2e81c6b519c229f0af3cbb51896cce7ec@sha256:7b65d15b092145ba91a899877932244fea61e11dd0f303e7f6129fafa3caded6
          name: container-image
